name: "Anchor Publish"
description: "Publishes a verifiable build to anchor"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-anchor/
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: ~/.cargo/bin/anchor build --verifiable
      shell: bash
