name: "Update cargo version"
description: "Update cargo version"
inputs:
  semvar:
    description: "Version update to make"
    required: true

permissions:
  contents: write
  package: write

# '${{ inputs.cargo-path }}',
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Update cargo version
      uses: actions/github-script@v4
      id: update-cargo-version
      with:
        script: |
          const script = require('.github/actions/update-cargo-version/script.js')

  # yarn install
  # const toml = require('@iarna/toml')
  # const result = await script({github, context, core, fs, toml}, ${{ inputs.semvar }})
  # const fs = require('fs')
  # console.log(result)

  # cargo-path:
  #   description: "Version update to make"
  #   required: true
  # cargo-path: ./newworld/program/Cargo.toml
