name: "Update cargo version"
description: "Update cargo version"
inputs:
  semvar:
    description: "Version update to make"
    required: true

permissions:
  contents: write
  package: write

# '${{ inputs.cargo-path }}',
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: yarn global add @iarna/toml
      shell: bash

    - name: Dump dir contents
      run: |
        pwd ~/.config
        ls ~/.config/yarn/global/node_modules/@iarna/toml
      shell: bash

    - name: Update cargo version
      uses: actions/github-script@v4
      id: update-cargo-version
      with:
        script: |
          const toml = require('/home/runner/work/newworld/newworld/yarn/global/node_modules/@iarna/toml/toml.js')
          const script = require('.github/actions/update-cargo-version/script.js')

  # const toml = require('@iarna/toml')
  # const result = await script({github, context, core, fs, toml}, ${{ inputs.semvar }})
  # const fs = require('fs')
  # console.log(result)

  # cargo-path:
  #   description: "Version update to make"
  #   required: true
  # cargo-path: ./newworld/program/Cargo.toml
