name: "Update cargo version"
description: "Update cargo version"
inputs:
  semvar:
    description: "Version update to make"
    required: true
  cargo-path:
    description: "Version update to make"
    required: true

outputs:
  version:
    description: Updated version based on semvar convention
    value: ${{ steps.set-updated-version.outputs.version }}

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Install dependency packages for script
      run: |
        yarn init --yes
        yarn add @iarna/toml
      shell: bash

    - name: Update cargo version
      uses: actions/github-script@v4
      id: update-cargo-version
      with:
        script: |
          const toml = require('@iarna/toml')
          const script = require('.github/actions/update-cargo-version/script.js')
          const updatedVersion = script({github, context, core, toml}, '${{ inputs.cargo-path }}', '${{ inputs.semvar }}')
          console.log('updatedVersion: ', updatedVersion);

    - name: Set updated version
      id: set-updated-version
      # env.UPDATED_VERSION exported from script.js
      run: echo "::set-output name=version::${{ env.UPDATED_VERSION }}"
      shell: bash
