name: "Update cargo version"
description: "Update cargo version"
inputs:
  semvar:
    description: "Version update to make"
    required: true

  cargo-path:
    description: "Version update to make"
    required: true

permissions:
  contents: write
  package: write

# '${{ inputs.cargo-path }}',
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Update cargo version
      uses: actions/github-script@v6
      id: update-cargo-version
      with:
        script: |
          yarn add fs @iarna/toml
          const fs = require('fs')
          const toml = require('@iarna/toml')
          const script = require('.github/actions/update-cargo-version/script.js')
          const result = await script({github, context, core, fs, toml}, ${{ inputs.semvar }})
          console.log(result)
