name: Setup Anchor
description: "Setup Anchor"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      name: Cache Anchor ClI
      id: cache-anchor-CLI
      with:
        path: |
          ~/.cargo/bin/anchor
        key: anchor-cli-${{ runner.os }}-${{ env.ANCHOR_VERSION }}

    - name: Install Anchor
      if: steps.cache-anchor-cli.outputs.cache-hit != 'true'
      run: cargo install --git https://github.com/project-serum/anchor --tag "v$ANCHOR_VERSION" anchor-cli --locked
      shell: bash
