name: "Setup AWS environment variables"
description: "Export AWS environment variables to common GH context"
runs:
  using: "composite"
  steps:
    # values stored in secrets because updates do not require a code change
    - run: echo "BINARY_STORAGE_ACCOUNT_ID=${{ secrets.BINARY_STORAGE_ACCOUNT_ID }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "BINARY_STORAGE_REGION=${{ secrets.BINARY_STORAGE_REGION }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "BINARY_STORAGE_ROLE=${{ secrets.BINARY_STORAGE_ROLE }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "BINARY_STORAGE_BUCKET=${{ secrets.BINARY_STORAGE_BUCKET }}" >> $GITHUB_ENV
      shell: bash
