name: "Publish to NPM registry and Github"
description: "Publish to NPM registry and Github"
inputs:
  node-version:
    description: "Path to the file to upload"
    required: true
  # cannot load token directly in action, so we need to pass it in
  npm-token:
    description: "Path to the file to upload"
    required: true
  github-token:
    description: "Path to the file to upload"
    required: true
  package-name:
    description: "Path to the file to upload"
    required: true
  path-to-package-json:
    description: "Path to the file to upload"
    required: true
  pull-number:
    description: "Path to the file to upload"
    required: true
  branch:
    description: "Path to the file to upload"
    required: true

permissions:
  id-token: read
  contents: write # for file updates
  packages: write # for publish

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
        cache-dependency-path: ${{ inputs.path-to-package-json}}/yarn.lock
        registry-url: "https://registry.npmjs.org"
    - name: Install dependencies
      shell: bash
      run: yarn install

    # todo: check if any rust files actually changed in this package?
    # -> then, check in next step

    - name: Fetch review comments for PR
      uses: ./.github/actions/fetch-pr-review-comments
      id: fetch-pr-review-comments
      with:
        pull-number: ${{ inputs.pull-number }}

    - name: npm login
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > ~/.npmrc
      env:
        NPM_PUBLISH_TOKEN: ${{ inputs.npm-token }}

    #  install
    - name: Upgrade package version
      if: ${{ steps.fetch-pr-review-comments.outputs.version != 'none' }}
      id: update-package-version
      shell: bash
      run: |
        cd $PATH_TO_PACKAGE_JSON
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git log
        npm version ${{ steps.fetch-pr-review-comments.outputs.version }}
        git log
        cat package.json
      env:
        PATH_TO_PACKAGE_JSON: ${{ inputs.path-to-package-json }}

    - name: Publish artifacts
      run: npm publish
      shell: bash
      env:
        NPM_PUBLISH_TOKEN: ${{ inputs.npm-token }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github-token }}
        branch: ${{ inputs.branch }}
