name: "Fetch PR labels by name"
description: "Fetch label names for a given PR"
inputs:
  owner:
    description: "Path to the file to upload"
    required: true
  repo:
    description: "Path to the file to upload"
    required: true
  pull-number:
    description: "Path to the file to upload"
    required: true

outputs:
  labels:
    description: Label names
    value: ${{ steps.set-output-for-labels.outputs.labels }}

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Get PR info and parse label names
      uses: actions/github-script@v4
      id: set-result
      with:
        script: |
          const request = {
            owner: ${{ inputs.owner }},
            repo: ${{ inputs.repo }},
            pull_number: ${{ inputs.pull-number }}
          }
          core.info(`Getting PR #${request.pull-number} from ${request.owner}/${request.repo}`)
          try {
            const { data } = await github.pulls.get(request)
            core.info(`Got PR data: ${JSON.stringify(data)}`)
            const labels = data.labels.length > 0 ? data.labels.map((label) => label.name) : []
            core.info(`Found ${labels.length} labels: ${labels}`)
            return labels
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }

    - name: Set output labels
      id: set-output-for-labels
      run: echo "::set-output name=labels::$LABELS"
      shell: bash
      env:
        LABELS: ${{steps.set-result.outputs.result}}
