name: "Make version changes"
description: "Make version changes"
inputs:
  changed-packages:
    description: "Changed packages - in format of <package>/<type>"
    required: true
  versioning:
    description: "Versioning command(s)"
    required: true
  # branch:
  #   description: "Branch to checkout"
  #   required: true

runs:
  using: "composite"
  steps:
    - name: Install cargo-release
      run: cargo install cargo-release

    # - uses: actions/checkout@v3

    - name: Make version changes
      uses: actions/github-script@v4
      with:
        script: |
          const script = require('.github/actions/make-version-changes/script.js')
          await script({github, context, core}, ${{ inputs.changed-packages }}, ${{ inputs.versioning }})
