name: "Assert changed files in a PR"
description: "Assert changed files in a PR"
inputs:
  pull-number:
    description: "Path to the file to upload"
    required: true
  # can optionally set required = false
  package-name:
    description: "Scope of package to assert"
    required: true
  extensions:
    description: "Scope of file extensions to assert"
    required: true
  # can also add `excludes` parameter to filter out certain files

outputs:
  assertion:
    description: Version
    value: ${{ steps.set-assertion.outputs.assertion }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Check changed files against target package and file types
      uses: actions/github-script@v4
      with:
        script: |
          const script = require('.github/actions/assert-changed-files/script.js')
          await script({github, context, core}, ${{ inputs.pull-number }}, '${{ inputs.package-name }}', '${{ inputs.extensions }}')

    - name: Set assertion from comments
      id: set-assertion
      # env.ASSERTION exported from script.js
      run: echo "::set-output name=assertion::${{ env.ASSERTION }}"
      shell: bash

# - name: Assert changed files
#   uses: ./.github/actions/assert-changed-files
#   id: assert-changed-files
#   with:
#     pull-number: ${{ inputs.pull-number }}
#     package-name: ${{ inputs.package-name }}
#     extensions: '["rs"]'
