name: "Fetch version from PR review"
description: "Fetch version from PR review"
inputs:
  owner:
    description: "Path to the file to upload"
    required: true
  repo:
    description: "Path to the file to upload"
    required: true
  pull_number:
    description: "Path to the file to upload"
    required: true

outputs:
  labels:
    description: Version
    value: ${{ steps.set-version-from-comments.outputs.version }}

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Map review comments to version
      uses: actions/github-script@v4
      id: fetch-pr-review-version
      with:
        script: |
          const script = require('.github/actions/fetch-pr-review-comments/script.js')
          await script({github, context, core, ${{ inputs.owner }}, ${{ inputs.repo }}, ${{ inputs.pull_number }}})

    - name: Set version from comments
      id: set-version-from-comments
      run: echo "::set-output name=version::$VERSION"
      shell: bash
      env:
        VERSION: ${{steps.fetch-pr-review-version.outputs.version}}
