name: "Fetch version from PR review"
description: "Fetch version from PR review"
inputs:
  pull-number:
    description: "Path to the file to upload"
    required: true

outputs:
  version:
    description: Version
    value: ${{ steps.set-version-from-comments.outputs.version }}

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Map review comments to version
      uses: actions/github-script@v4
      id: fetch-pr-review-version
      with:
        script: |
          const script = require('.github/actions/fetch-pr-review-comments/script.js')
          const result = await script({github, context, core}, ${{ inputs.pull-number }})
          console.log(result)

    - name: Set version from comments
      id: set-version-from-comments
      # env.REVIEW_VERSION exported from script.js
      run: echo "::set-output name=version::${{ env.REVIEW_VERSION }}"
      shell: bash
