#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ -z "$LINT_RUST" || "$LINT_RUST" = false ]]; then
  echo "Skipping Rust lint since LINT_RUST is undefined or false"
else
  if [ -z "$(git diff --name-only **/*.rs)" ]; then
    echo "No Rust changes to lint"
  else
    echo "Linting Rust changes"
    # todo
  fi
fi

if [ -z "$(git diff --name-only **/*.{ts,js})" ]; then
  echo "No TS changes to lint"
else
  echo "Linting TS changes"
fi
