# This is a basic workflow to help you get started with Actions

name: pr-comment

on:
  pull_request_review:
    types: [submitted, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  NODE_VERSION: 17.0.1
  ANCHOR_VERSION: 0.22.0
  SOLANA_VERSION_STABLE: 1.9.22
  RUST_TOOLCHAIN: stable
  PROGRAM_NAME: newworld

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  fetch-changed-files:
    runs-on: ubuntu-latest
    id: fetch-changed-files
    steps:
      - uses: actions/checkout@v2
      - name: Fetch changed files
        uses: ./.github/actions/fetch-changed-files
        with:
          pull-number: 18

  print-review-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print review body
        run: |
          echo "${{ github.review.body }}"
          echo "${{ github.review.author_association }}"
          echo "${{ github.pull_request.number }}"

  # map fetched changed files to package / lang (list)
  # fetch version command from comment (1 for now)
  # run update version on all packages that match command
  # -- route differently based on package manager
