name: PR merge flow

on:
  pull_request:
    types:
      - closed
    branches: [main]

permissions:
  id-token: read
  contents: write
  packages: write # for publish

# env:
#   NODE_VERSION: 17.0.1
#   ANCHOR_VERSION: 0.22.0
#   SOLANA_VERSION_STABLE: 1.9.22
#   RUST_TOOLCHAIN: stable
#   PROGRAM_NAME: newworld
#   ACCOUNT_ID: 813125037859
#   REGION: us-east-1
#   ROLE: uploadToS3Role
#   BUCKET: programbuildsinfrastack-verifiablebuildbinariesb-1umx6gqtqe6gl

defaults:
  run:
    working-directory: ./newworld/js

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pr-merge-worklfow:
    name: PR merge workflow
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Publish updated artifacts to NPM and Github
        uses: ./.github/actions/publish-to-npm
        id: publish-to-npm
        with:
          npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: newworld
          path-to-package-dir: ./newworld/js
          pull-number: ${{ github.event.number }}
          branch: ${{ github.ref }}
